### ISSUE TITLE
add new field vendimiado to campo model

### ISSUE THREAD

**Issue by Japoivvb** [Rodcar2000/daniel_rodriguez_uf2_p2#7]
1. add vendimiado attribute to campo model, it sets false and changes true after vendimia

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Japoivvb** [comment]
@Rodcar2000 please fix this issue to pass UF3, you did the big part of job in #6 it should not bring you more than 2 hours

**Comment by Rodcar2000** [comment]
### **Resolución Issue 7**
Añadimos el campo en addCampo y lo inicializamos a false:
![image](https://github.com/Rodcar2000/daniel_rodriguez_uf2_p2/assets/155441265/b53db8d6-e275-40ea-86b4-de35dc4d831f)
Lo actualizamos después de Vendimia:
![image](https://github.com/Rodcar2000/daniel_rodriguez_uf2_p2/assets/155441265/8e2c865f-c2f7-4b94-9ff1-d0ed99269f37)
**Datos en la BBDD**
![image](https://github.com/Rodcar2000/daniel_rodriguez_uf2_p2/assets/155441265/dfa0cedd-f2ef-48d7-9b99-0c950ff05344)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
great job @Rodcar2000  as expected from you, quality and quantity.
